/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package feelsmusicinc;

import java.awt.CardLayout;
import java.awt.Toolkit;
import java.io.InputStream;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.text.StyleConstants.setIcon;
import javazoom.jl.player.Player;
    
/**
 *
 * @author Guilherme
 */
public class TelaFM extends javax.swing.JFrame {
   
    private boolean FM;
    private int cont = 0;
    private String[] musicas = new String[3];
    private String[][] descricao = {{"Cat Dealers, LOthief, Santti","Sunshine","2017"},
                                    {"Chris Lake feat Alexis Roberts","Black Book","2018"},
                                    {"Evokings","On The Floor","2018"}
                                    };
    private Player ply;
    private boolean pl;
    Musica mp3;
    
    
    
    Clientes cl = new Clientes();

    /**
     * Creates new form TelaFM
     */
    public TelaFM() {
        musicas[0] = "";
        musicas[1] = "";
        musicas[2] = "";

        
        
        initComponents();
        setIcon();
        
        BVoltar.setEnabled(false);
        BPause.setEnabled(false);
        
        BFunk.setVisible(false);
        BSamba.setVisible(false);
        BRap.setVisible(false);
        BEletronica.setVisible(false);
        BRock.setVisible(false);
        BSertanejo.setVisible(false);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        PLogin = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PSenha = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        login_nick = new javax.swing.JTextField();
        BEntrarLogin = new javax.swing.JButton();
        LNick = new javax.swing.JLabel();
        LSenha = new javax.swing.JLabel();
        BCadastrar = new javax.swing.JButton();
        LErro = new javax.swing.JLabel();
        PCadastro = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        LNome = new javax.swing.JLabel();
        TNome = new javax.swing.JTextField();
        LIdade = new javax.swing.JLabel();
        TEmail = new javax.swing.JTextField();
        LEmail = new javax.swing.JLabel();
        TIdade = new javax.swing.JTextField();
        LNickC = new javax.swing.JLabel();
        TNickC = new javax.swing.JTextField();
        LSenhaC = new javax.swing.JLabel();
        PSenhaC = new javax.swing.JPasswordField();
        LSenhaCC = new javax.swing.JLabel();
        PSenhaCC = new javax.swing.JPasswordField();
        LSexo = new javax.swing.JLabel();
        RMasc = new javax.swing.JRadioButton();
        RFem = new javax.swing.JRadioButton();
        RTermos = new javax.swing.JRadioButton();
        BEntrarCadastro = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        BVoltarLogin = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        LTermos = new javax.swing.JLabel();
        PDirecionamento = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        BSair = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        BVamoDale = new javax.swing.JButton();
        BNostalgia = new javax.swing.JButton();
        BOdio = new javax.swing.JButton();
        BTriste = new javax.swing.JButton();
        BApaixonado = new javax.swing.JButton();
        BInspirado = new javax.swing.JButton();
        BDeus = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        PMp3 = new javax.swing.JPanel();
        jPanel10 = new javax.swing.JPanel();
        LMusica = new javax.swing.JLabel();
        LArtista = new javax.swing.JLabel();
        LAlbum = new javax.swing.JLabel();
        LAno = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        BPlay = new javax.swing.JButton();
        BPause = new javax.swing.JButton();
        BVoltar = new javax.swing.JButton();
        BAvancar = new javax.swing.JButton();
        BSairMp3 = new javax.swing.JButton();
        PGenero = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        BSamba = new javax.swing.JButton();
        BFunk = new javax.swing.JButton();
        BRap = new javax.swing.JButton();
        BEletronica = new javax.swing.JButton();
        BRock = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        BVoltarDirec = new javax.swing.JButton();
        BSertanejo = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 140, 0), 5, true));
        jPanel1.setForeground(new java.awt.Color(255, 102, 0));
        jPanel1.setMaximumSize(new java.awt.Dimension(32767, 22767));
        jPanel1.setPreferredSize(new java.awt.Dimension(1342, 743));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        MainPanel.setMinimumSize(new java.awt.Dimension(1000, 690));
        MainPanel.setPreferredSize(new java.awt.Dimension(1345, 743));
        MainPanel.setLayout(new java.awt.CardLayout());

        PLogin.setMinimumSize(new java.awt.Dimension(0, 0));
        PLogin.setPreferredSize(new java.awt.Dimension(1000, 700));
        PLogin.setRequestFocusEnabled(false);
        PLogin.setVerifyInputWhenFocusTarget(false);
        PLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 140, 0), 5, true));
        jPanel2.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel2.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 2, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 140, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Bem vindo a Feels Music ");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 258));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel1.setPreferredSize(new java.awt.Dimension(500, 100));
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 80));

        PSenha.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PSenhaActionPerformed(evt);
            }
        });
        jPanel2.add(PSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 420, 160, 25));

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/feels.png"))); // NOI18N
        jLabel8.setText("jLabel8");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(355, 110, 270, -1));

        login_nick.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                login_nickActionPerformed(evt);
            }
        });
        jPanel2.add(login_nick, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 160, 25));

        BEntrarLogin.setBackground(new java.awt.Color(255, 140, 0));
        BEntrarLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BEntrarLogin.setText("Entrar");
        BEntrarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEntrarLoginActionPerformed(evt);
            }
        });
        jPanel2.add(BEntrarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 480, 110, -1));

        LNick.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LNick.setForeground(new java.awt.Color(255, 140, 0));
        LNick.setText("Nickname");
        jPanel2.add(LNick, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 390, -1, -1));

        LSenha.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        LSenha.setForeground(new java.awt.Color(255, 140, 0));
        LSenha.setText("Senha");
        jPanel2.add(LSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 420, -1, -1));

        BCadastrar.setBackground(new java.awt.Color(255, 140, 0));
        BCadastrar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BCadastrar.setText("Cadastrar");
        BCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BCadastrarActionPerformed(evt);
            }
        });
        jPanel2.add(BCadastrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 520, 110, -1));

        LErro.setForeground(new java.awt.Color(255, 0, 0));
        jPanel2.add(LErro, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 450, 90, 20));

        PLogin.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        MainPanel.add(PLogin, "PLogin");

        PCadastro.setBackground(new java.awt.Color(255, 140, 0));
        PCadastro.setForeground(new java.awt.Color(255, 140, 0));
        PCadastro.setMinimumSize(new java.awt.Dimension(1000, 600));
        PCadastro.setPreferredSize(new java.awt.Dimension(1000, 600));
        PCadastro.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBackground(new java.awt.Color(0, 0, 0));
        jPanel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 140, 0), 5, true));
        jPanel4.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel4.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LNome.setBackground(new java.awt.Color(255, 140, 0));
        LNome.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LNome.setForeground(new java.awt.Color(255, 140, 0));
        LNome.setText("Nome Completo");
        jPanel4.add(LNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 170, 25));
        jPanel4.add(TNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 160, 25));

        LIdade.setBackground(new java.awt.Color(255, 140, 0));
        LIdade.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LIdade.setForeground(new java.awt.Color(255, 140, 0));
        LIdade.setText("Idade");
        jPanel4.add(LIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 170, 25));
        jPanel4.add(TEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 200, 160, 30));

        LEmail.setBackground(new java.awt.Color(255, 140, 0));
        LEmail.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LEmail.setForeground(new java.awt.Color(255, 140, 0));
        LEmail.setText("E-mail");
        jPanel4.add(LEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, -1, -1));
        jPanel4.add(TIdade, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 240, 160, 25));

        LNickC.setBackground(new java.awt.Color(255, 140, 0));
        LNickC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LNickC.setForeground(new java.awt.Color(255, 140, 0));
        LNickC.setText("Nickname");
        jPanel4.add(LNickC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 170, 25));
        jPanel4.add(TNickC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 280, 160, 25));

        LSenhaC.setBackground(new java.awt.Color(255, 140, 0));
        LSenhaC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LSenhaC.setForeground(new java.awt.Color(255, 140, 0));
        LSenhaC.setText("Senha");
        jPanel4.add(LSenhaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 320, 170, 25));
        jPanel4.add(PSenhaC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 320, 160, 25));

        LSenhaCC.setBackground(new java.awt.Color(255, 140, 0));
        LSenhaCC.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LSenhaCC.setForeground(new java.awt.Color(255, 140, 0));
        LSenhaCC.setText("Confirmar Senha");
        jPanel4.add(LSenhaCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 360, 170, 25));
        jPanel4.add(PSenhaCC, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 360, 160, 25));

        LSexo.setBackground(new java.awt.Color(255, 140, 0));
        LSexo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        LSexo.setForeground(new java.awt.Color(255, 140, 0));
        LSexo.setText("Sexo");
        jPanel4.add(LSexo, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 170, 25));

        RMasc.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(RMasc);
        RMasc.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RMasc.setForeground(new java.awt.Color(255, 140, 0));
        RMasc.setText("Masc");
        jPanel4.add(RMasc, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 400, 60, -1));

        RFem.setBackground(new java.awt.Color(0, 0, 0));
        buttonGroup1.add(RFem);
        RFem.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RFem.setForeground(new java.awt.Color(255, 140, 0));
        RFem.setText("Fem");
        jPanel4.add(RFem, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, 60, -1));

        RTermos.setBackground(new java.awt.Color(0, 0, 0));
        RTermos.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        RTermos.setForeground(new java.awt.Color(255, 140, 0));
        RTermos.setText("Li e aceito os");
        jPanel4.add(RTermos, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 450, -1, -1));

        BEntrarCadastro.setBackground(new java.awt.Color(255, 153, 0));
        BEntrarCadastro.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BEntrarCadastro.setText("Inscrever-se");
        BEntrarCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEntrarCadastroActionPerformed(evt);
            }
        });
        jPanel4.add(BEntrarCadastro, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 490, 160, 25));

        jLabel3.setBackground(new java.awt.Color(255, 140, 0));
        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 140, 0));
        jLabel3.setText("Já tem cadastro?");
        jPanel4.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 530, -1, -1));

        BVoltarLogin.setBackground(new java.awt.Color(255, 153, 0));
        BVoltarLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        BVoltarLogin.setText("Login");
        BVoltarLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVoltarLoginActionPerformed(evt);
            }
        });
        jPanel4.add(BVoltarLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 550, 160, 25));

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 140, 0));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Cadastro");
        jPanel4.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 80));

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("jLabel7");
        jPanel4.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(1130, 350, 50, 30));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagem1111.png"))); // NOI18N
        jLabel11.setText("jLabel11");
        jPanel4.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 170, 360, 320));

        LTermos.setFont(new java.awt.Font("Tahoma", 2, 14)); // NOI18N
        LTermos.setForeground(new java.awt.Color(255, 153, 0));
        LTermos.setText("Termos de Uso");
        LTermos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                LTermosMouseClicked(evt);
            }
        });
        jPanel4.add(LTermos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 450, 130, 20));

        PCadastro.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        MainPanel.add(PCadastro, "PCadastro");

        PDirecionamento.setPreferredSize(new java.awt.Dimension(1000, 600));
        PDirecionamento.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(0, 0, 0));
        jPanel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 140, 0), 5, true));
        jPanel5.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel5.setName(""); // NOI18N
        jPanel5.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BSair.setBackground(new java.awt.Color(255, 153, 0));
        BSair.setText("VOLTAR");
        BSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSairActionPerformed(evt);
            }
        });
        jPanel5.add(BSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 140, 0));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Como você está se sentindo hoje?");
        jLabel4.setToolTipText("");
        jPanel5.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 80));

        BVamoDale.setBackground(new java.awt.Color(255, 140, 0));
        BVamoDale.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BVamoDale.setText("\"Vamo Dale\"");
        BVamoDale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVamoDaleActionPerformed(evt);
            }
        });
        jPanel5.add(BVamoDale, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 510, 280, 30));

        BNostalgia.setBackground(new java.awt.Color(255, 140, 0));
        BNostalgia.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BNostalgia.setText("Querendo Nostálgia");
        BNostalgia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BNostalgiaActionPerformed(evt);
            }
        });
        jPanel5.add(BNostalgia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 280, 30));

        BOdio.setBackground(new java.awt.Color(255, 140, 0));
        BOdio.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BOdio.setText("Com ódio");
        BOdio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BOdioActionPerformed(evt);
            }
        });
        jPanel5.add(BOdio, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 280, 30));

        BTriste.setBackground(new java.awt.Color(255, 140, 0));
        BTriste.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BTriste.setText("Triste");
        BTriste.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTristeActionPerformed(evt);
            }
        });
        jPanel5.add(BTriste, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 280, 30));

        BApaixonado.setBackground(new java.awt.Color(255, 140, 0));
        BApaixonado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BApaixonado.setText("Apaixonado");
        BApaixonado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BApaixonadoActionPerformed(evt);
            }
        });
        jPanel5.add(BApaixonado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 280, 30));

        BInspirado.setBackground(new java.awt.Color(255, 140, 0));
        BInspirado.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BInspirado.setText("Inspirado");
        BInspirado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BInspiradoActionPerformed(evt);
            }
        });
        jPanel5.add(BInspirado, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 280, 30));

        BDeus.setBackground(new java.awt.Color(255, 140, 0));
        BDeus.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BDeus.setText("Querendo Momento com Deus");
        BDeus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BDeusActionPerformed(evt);
            }
        });
        jPanel5.add(BDeus, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 280, 30));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/EMOJIIS.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 170, -1, -1));

        PDirecionamento.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        MainPanel.add(PDirecionamento, "PDirecionamento");
        PDirecionamento.getAccessibleContext().setAccessibleParent(PDirecionamento);

        PMp3.setBackground(new java.awt.Color(0, 0, 0));
        PMp3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 140, 0), 5, true));
        PMp3.setMinimumSize(new java.awt.Dimension(1010, 690));
        PMp3.setPreferredSize(new java.awt.Dimension(1345, 743));
        PMp3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel10.setBackground(new java.awt.Color(0, 0, 0));
        jPanel10.setMinimumSize(new java.awt.Dimension(1000, 600));
        jPanel10.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LMusica.setBackground(new java.awt.Color(255, 140, 0));
        LMusica.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        LMusica.setForeground(new java.awt.Color(255, 140, 0));
        LMusica.setText("Música:");
        jPanel10.add(LMusica, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 92, 342, 46));

        LArtista.setBackground(new java.awt.Color(255, 140, 0));
        LArtista.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        LArtista.setForeground(new java.awt.Color(255, 140, 0));
        LArtista.setText("Artista:");
        jPanel10.add(LArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 144, 342, 46));

        LAlbum.setBackground(new java.awt.Color(255, 140, 0));
        LAlbum.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        LAlbum.setForeground(new java.awt.Color(255, 140, 0));
        LAlbum.setText("Álbum:");
        jPanel10.add(LAlbum, new org.netbeans.lib.awtextra.AbsoluteConstraints(171, 196, 342, 46));

        LAno.setBackground(new java.awt.Color(255, 140, 0));
        LAno.setFont(new java.awt.Font("Tahoma", 2, 24)); // NOI18N
        LAno.setForeground(new java.awt.Color(255, 140, 0));
        LAno.setText("Ano de Lançamento: ");
        jPanel10.add(LAno, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 410, 46));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/novo.gif"))); // NOI18N
        jLabel12.setText("jLabel12");
        jPanel10.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, -1, 400));

        PMp3.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 930, 390));

        BPlay.setBackground(new java.awt.Color(255, 140, 0));
        BPlay.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BPlay.setText("Tocar");
        BPlay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPlayActionPerformed(evt);
            }
        });
        PMp3.add(BPlay, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 483, -1, -1));

        BPause.setBackground(new java.awt.Color(255, 140, 0));
        BPause.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BPause.setText("Parar");
        BPause.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BPauseActionPerformed(evt);
            }
        });
        PMp3.add(BPause, new org.netbeans.lib.awtextra.AbsoluteConstraints(294, 483, -1, -1));

        BVoltar.setBackground(new java.awt.Color(255, 140, 0));
        BVoltar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BVoltar.setText("<<");
        BVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVoltarActionPerformed(evt);
            }
        });
        PMp3.add(BVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(444, 483, -1, -1));

        BAvancar.setBackground(new java.awt.Color(255, 140, 0));
        BAvancar.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        BAvancar.setText(">>");
        BAvancar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BAvancarActionPerformed(evt);
            }
        });
        PMp3.add(BAvancar, new org.netbeans.lib.awtextra.AbsoluteConstraints(529, 483, -1, -1));

        BSairMp3.setBackground(new java.awt.Color(255, 153, 0));
        BSairMp3.setText("VOLTAR");
        BSairMp3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSairMp3ActionPerformed(evt);
            }
        });
        PMp3.add(BSairMp3, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 80, 30));

        MainPanel.add(PMp3, "PMp3");

        PGenero.setMinimumSize(new java.awt.Dimension(1000, 600));
        PGenero.setOpaque(false);
        PGenero.setPreferredSize(new java.awt.Dimension(1000, 600));
        PGenero.setRequestFocusEnabled(false);
        PGenero.setVerifyInputWhenFocusTarget(false);
        PGenero.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 0, 0));
        jPanel7.setPreferredSize(new java.awt.Dimension(1342, 743));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel8.setBackground(new java.awt.Color(0, 0, 0));
        jPanel8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 140, 0), 5, true));
        jPanel8.setMaximumSize(new java.awt.Dimension(1000, 600));
        jPanel8.setPreferredSize(new java.awt.Dimension(1000, 600));
        jPanel8.setRequestFocusEnabled(false);
        jPanel8.setVerifyInputWhenFocusTarget(false);
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        BSamba.setBackground(new java.awt.Color(255, 140, 0));
        BSamba.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BSamba.setText("Pagode / Samba");
        BSamba.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSambaActionPerformed(evt);
            }
        });
        jPanel8.add(BSamba, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 330, 220, 30));

        BFunk.setBackground(new java.awt.Color(255, 140, 0));
        BFunk.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BFunk.setText("Funk");
        BFunk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BFunkActionPerformed(evt);
            }
        });
        jPanel8.add(BFunk, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, 220, 30));

        BRap.setBackground(new java.awt.Color(255, 140, 0));
        BRap.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BRap.setText("Hip Hop / Rap");
        BRap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRapActionPerformed(evt);
            }
        });
        jPanel8.add(BRap, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, 220, 30));

        BEletronica.setBackground(new java.awt.Color(255, 140, 0));
        BEletronica.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BEletronica.setText("Música eletrônica");
        BEletronica.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BEletronicaActionPerformed(evt);
            }
        });
        jPanel8.add(BEletronica, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, 220, 30));

        BRock.setBackground(new java.awt.Color(255, 140, 0));
        BRock.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BRock.setText("Rock / Pop");
        BRock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BRockActionPerformed(evt);
            }
        });
        jPanel8.add(BRock, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, 220, 30));

        jLabel5.setBackground(new java.awt.Color(255, 153, 0));
        jLabel5.setFont(new java.awt.Font("Tahoma", 2, 36)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Escolha seu gênero preferido");
        jPanel8.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 980, 80));

        BVoltarDirec.setText("VOLTAR");
        BVoltarDirec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BVoltarDirecActionPerformed(evt);
            }
        });
        jPanel8.add(BVoltarDirec, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 30, 80, 30));

        BSertanejo.setBackground(new java.awt.Color(255, 140, 0));
        BSertanejo.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        BSertanejo.setText("Sertanejo");
        BSertanejo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BSertanejoActionPerformed(evt);
            }
        });
        jPanel8.add(BSertanejo, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 450, 220, 30));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagem3.png"))); // NOI18N
        jLabel10.setText("jLabel10");
        jPanel8.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 160, 150));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagem4.png"))); // NOI18N
        jLabel9.setText("jLabel9");
        jPanel8.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 200, 150, 110));

        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/Imagem6.png"))); // NOI18N
        jLabel14.setText("jLabel14");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(750, 130, -1, -1));

        jPanel7.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 600));

        PGenero.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1000, 640));

        MainPanel.add(PGenero, "PGenero");
        PGenero.getAccessibleContext().setAccessibleName("");
        PGenero.getAccessibleContext().setAccessibleParent(PGenero);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 1000, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void setIcon(){
       setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("IconFM.png")));
    }

    private void BEntrarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEntrarLoginActionPerformed
        String senhaL = new String(PSenha.getPassword());
        String nickL = login_nick.getText();
       
        

        System.out.println(senhaL);
        System.out.println(nickL);
        if(cl.login(nickL, senhaL)){
            System.out.println("AUTENTICADO");
            CardLayout card = (CardLayout)MainPanel.getLayout();
            card.show(MainPanel,"PDirecionamento");
        }else{
            LErro.setText("Login Inválido!");
            System.out.println("NÃO AUTENTICADO");
        }
       
        
        
    }//GEN-LAST:event_BEntrarLoginActionPerformed

    private void BCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BCadastrarActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel,"PCadastro");
    }//GEN-LAST:event_BCadastrarActionPerformed

    private void BSertanejoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSertanejoActionPerformed
        generomusical = "sertanejo" ;
        modificaMusica();
    }//GEN-LAST:event_BSertanejoActionPerformed

    private void BSambaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSambaActionPerformed
        generomusical = "samba" ;
        modificaMusica();
    
    }//GEN-LAST:event_BSambaActionPerformed

    private void BEletronicaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEletronicaActionPerformed
        generomusical = "eletronica" ;
        modificaMusica();
        
    }//GEN-LAST:event_BEletronicaActionPerformed

    private void BFunkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BFunkActionPerformed
        generomusical = "funk" ;
        modificaMusica();
    }//GEN-LAST:event_BFunkActionPerformed

    private void BRapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRapActionPerformed
        generomusical = "rap" ;
        modificaMusica();
    }//GEN-LAST:event_BRapActionPerformed

    private void BRockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BRockActionPerformed
       generomusical = "rock";
       modificaMusica();
        
    }//GEN-LAST:event_BRockActionPerformed

    private void BVoltarDirecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVoltarDirecActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel,"PDirecionamento");
    }//GEN-LAST:event_BVoltarDirecActionPerformed

    private void PSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PSenhaActionPerformed

    private void BDeusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BDeusActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel,"PGenero");

        BFunk.setVisible(true);
        BSamba.setVisible(true);
        BRock.setVisible(true);
        BRap.setVisible(true);
        BRock.setVisible(true);
        BEletronica.setVisible(true);
        BSertanejo.setVisible(true);
        direcionamento = "deus";
    }//GEN-LAST:event_BDeusActionPerformed

    private void BInspiradoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BInspiradoActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel,"PGenero");

        BFunk.setVisible(true);
        BSamba.setVisible(true);
        BRock.setVisible(true);
        BRap.setVisible(true);
        BRock.setVisible(true);
        BEletronica.setVisible(true);
        BSertanejo.setVisible(true);
        direcionamento = "inspirado";
    }//GEN-LAST:event_BInspiradoActionPerformed

    private void BApaixonadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BApaixonadoActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel,"PGenero");

        BFunk.setVisible(true);
        BSamba.setVisible(true);
        BRock.setVisible(true);
        BRap.setVisible(true);
        BRock.setVisible(true);
        BEletronica.setVisible(true);
        BSertanejo.setVisible(true);
        direcionamento = "apaixonado";
    }//GEN-LAST:event_BApaixonadoActionPerformed

    private void BTristeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTristeActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel,"PGenero");

        BFunk.setVisible(true);
        BSamba.setVisible(true);
        BRock.setVisible(true);
        BRap.setVisible(true);
        BRock.setVisible(true);
        BEletronica.setVisible(true);
        BSertanejo.setVisible(true);
        direcionamento = "triste";
    }//GEN-LAST:event_BTristeActionPerformed

    private void BOdioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BOdioActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();

        card.show(MainPanel,"PGenero");

        BFunk.setVisible(true);
        BSamba.setVisible(true);
        BRock.setVisible(true);
        BRap.setVisible(true);
        BRock.setVisible(true);
        BEletronica.setVisible(true);
        BSertanejo.setVisible(true);
        direcionamento = "odio";
    }//GEN-LAST:event_BOdioActionPerformed

    private void BNostalgiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BNostalgiaActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel,"PGenero");

        BFunk.setVisible(true);
        BSamba.setVisible(true);
        BRock.setVisible(true);
        BRap.setVisible(true);
        BRock.setVisible(true);
        BEletronica.setVisible(true);
        BSertanejo.setVisible(true);
        direcionamento = "nostalgia";
    }//GEN-LAST:event_BNostalgiaActionPerformed

    private void BVamoDaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVamoDaleActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel,"PGenero");

        BFunk.setVisible(true);
        BSamba.setVisible(true);
        BRock.setVisible(true);
        BRap.setVisible(true);
        BRock.setVisible(true);
        BEletronica.setVisible(true);
        BSertanejo.setVisible(true);
        direcionamento = "vd";
    }//GEN-LAST:event_BVamoDaleActionPerformed

    private void BSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSairActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel,"PLogin");
    }//GEN-LAST:event_BSairActionPerformed

    private void BSairMp3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BSairMp3ActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel,"PGenero");
    }//GEN-LAST:event_BSairMp3ActionPerformed

    private void BAvancarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BAvancarActionPerformed
        BVoltar.setEnabled(true);

        if(cont<3){
            cont++;
            if(cont==2){
                BAvancar.setEnabled(false);
            }else{
                BAvancar.setEnabled(true);
            }
        }else{
            BAvancar.setEnabled(false);
        }
        if(direcionamento.equals ("inspirado") && (generomusical.equals ("eletronica"))){
            this.atualizar ();
        }
        LMusica.setText("Música: "+musicas[cont]);
    }//GEN-LAST:event_BAvancarActionPerformed

    private void BVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVoltarActionPerformed
        BAvancar.setEnabled(true);

        if(cont > 0){
            cont--;
            if(cont != 0){
                BVoltar.setEnabled(true);
            }else{
                BVoltar.setEnabled(false);
            }
        }else{
            BVoltar.setEnabled(false);
        }
        if(direcionamento.equals ("inspirado") && (generomusical.equals ("eletronica"))){
            this.atualizar ();
        }
        LMusica.setText("Música: "+musicas[cont]);
    }//GEN-LAST:event_BVoltarActionPerformed

    private void BPauseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPauseActionPerformed
        mp3.stop();
        BPause.setEnabled(false);
        BPlay.setEnabled(true);
    }//GEN-LAST:event_BPauseActionPerformed

    private void BPlayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BPlayActionPerformed
        mp3 = new Musica();
        mp3.start();

        LMusica.setText("Música: "+musicas[cont]);
        
        BPlay.setEnabled(false);
        BPause.setEnabled(true);
    }//GEN-LAST:event_BPlayActionPerformed

    private void login_nickActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_login_nickActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_login_nickActionPerformed

    private void BVoltarLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BVoltarLoginActionPerformed
        CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel,"PLogin");
    }//GEN-LAST:event_BVoltarLoginActionPerformed

    private void BEntrarCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BEntrarCadastroActionPerformed

        String senhaC = new String(PSenhaC.getPassword());
        String senhaCC = new String(PSenhaCC.getPassword());

        if(RTermos.isSelected()){
            if(senhaC.equals(senhaCC) ){

                cl.nome = TNome.getText();
                cl.idade = TIdade.getText();
                cl.email = TEmail.getText();
                cl.nick = TNickC.getText();
                
                if(RMasc.isSelected()){
                    cl.sexo = "Masculino";
                }else{
                    cl.sexo = "Feminino";
                }
                cl.cadastrar(TNickC.getText(), senhaC);
                System.out.println(cl.nome+"\n"+cl.idade+"\n"+cl.email+"\n"+cl.nick+"\n"+senhaC+"\n"+senhaCC);
                try {
                    JOptionPane.showMessageDialog(null,"Verifique seu e-mail para confirmação do cadastro.");
                    EnvioDeEmail email = new EnvioDeEmail();
                    email.enviarEmail(cl.email);
                    
                }catch(Exception ex){
                    JOptionPane.showMessageDialog(null,"Verifique seu e-mail para confirmação do cadastro.");  
                }
                
                
            }else{
                JOptionPane.showMessageDialog(null, "Senhas incompatíveis, tente novamente!");
            }
        }else{
            JOptionPane.showMessageDialog(null, "Você precisa aceitar os termos de uso para continuar.");
        }

    }//GEN-LAST:event_BEntrarCadastroActionPerformed

    private void LTermosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_LTermosMouseClicked
        
        // Colocar termos
        new Termos().setVisible(true);
    }//GEN-LAST:event_LTermosMouseClicked
     public void modificaMusica() {
         
        if ((direcionamento.equals ("vd") && (generomusical.equals("funk")))){
             System.out.println(cl.idade);
            cl.idadeconvertida = Integer.parseInt(cl.idade);
            System.out.println("kk");
            if (cl.idadeconvertida<18){
                musicas[0] = "Troféu do Ano";
                musicas[1] = "Troféu do Ano";
                musicas[2] = "Troféu do Ano";
                LArtista.setText("Jerry Smith & MC Nando DK ft. Cassula DJ");
                LAlbum.setText("Troféu do Ano");
                LAno.setText("2017");
            }
            
            if(cl.idadeconvertida>=18){
                musicas[0] = "Fazer Falta";
                musicas[1] = "Fazer Falta";
                musicas[2] = "Fazer Falta";
                LArtista.setText("MC Livinho");
                LAlbum.setText("Fazer Falta");
                LAno.setText("2017");
            }
        
        }else if(direcionamento.equals ("inspirado") && (generomusical.equals ("eletronica"))){
           musicas [0]= "Sunshine";

           musicas [1]= "Turn Of The Lights";
   
           musicas [2]= "On The Floor";
           
           this.atualizar();

        }else if(direcionamento.equals ("apaixonado") && (generomusical.equals ("samba"))){
           musicas [0]= "Pirata e Tesouro";
           musicas [1]= "Pirata e Tesouro";
           musicas [2]= "Pirata e Tesouro";
           LArtista.setText("Ferrugem");
           LAlbum.setText("Prazer, eu sou Ferrugem");
           LAno.setText("2017");
           
        }else if(direcionamento.equals ("triste") && (generomusical.equals ("samba"))){
           musicas [0]= "Viva a Vida";
           musicas [1]= "Viva a Vida";
           musicas [2]= "Viva a Vida";
           LArtista.setText("Turma do Pagode");
           LAlbum.setText("Misturadin");
           LAno.setText("2017");
                
        }else if(direcionamento.equals ("odio") && (generomusical.equals ("sertanejo"))){
            musicas[0]= "A Dama e o Vagabundo";
            musicas[1]= "A Dama e o Vagabundo";
            musicas[2]= "A Dama e o Vagabundo";
            LArtista.setText("Wesley Safadão");
            LAlbum.setText("WS In Miami Beach");
            LAno.setText("2017");
                
        }else if(direcionamento.equals ("deus") && (generomusical.equals ("rock"))){
            musicas[0]= "On My Own";
            musicas[1]= "End Of Me";
            musicas[2]= "Without You";
            LArtista.setText("Ashes Remain");
            LAlbum.setText("What I’ve Become");
            LAno.setText("2011");
                
        }else if(direcionamento.equals ("nostalgia") && (generomusical.equals ("rock"))){
            musicas[0]= "Its So Easy";
            musicas[1]= "Its So Easy";
            musicas[2]= "Its So Easy";
            LArtista.setText("Guns N' Roses");
            LAlbum.setText("Appetite For Destruction");
            LAno.setText("1987");
           
        }
         CardLayout card = (CardLayout)MainPanel.getLayout();
        card.show(MainPanel,"PMp3");
     }
     
     public void atualizar (){
          LArtista.setText(descricao[cont][0]);
          LAlbum.setText(descricao[cont][1]);
          LAno.setText(descricao[cont][2]);
     }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaFM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaFM().setVisible(true);
            }
        });
    }

    private String direcionamento;
    private String generomusical;
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BApaixonado;
    private javax.swing.JButton BAvancar;
    private javax.swing.JButton BCadastrar;
    private javax.swing.JButton BDeus;
    private javax.swing.JButton BEletronica;
    private javax.swing.JButton BEntrarCadastro;
    private javax.swing.JButton BEntrarLogin;
    private javax.swing.JButton BFunk;
    private javax.swing.JButton BInspirado;
    private javax.swing.JButton BNostalgia;
    private javax.swing.JButton BOdio;
    private javax.swing.JButton BPause;
    private javax.swing.JButton BPlay;
    private javax.swing.JButton BRap;
    private javax.swing.JButton BRock;
    private javax.swing.JButton BSair;
    private javax.swing.JButton BSairMp3;
    private javax.swing.JButton BSamba;
    private javax.swing.JButton BSertanejo;
    private javax.swing.JButton BTriste;
    private javax.swing.JButton BVamoDale;
    private javax.swing.JButton BVoltar;
    private javax.swing.JButton BVoltarDirec;
    private javax.swing.JButton BVoltarLogin;
    private javax.swing.JLabel LAlbum;
    private javax.swing.JLabel LAno;
    private javax.swing.JLabel LArtista;
    private javax.swing.JLabel LEmail;
    private javax.swing.JLabel LErro;
    private javax.swing.JLabel LIdade;
    private javax.swing.JLabel LMusica;
    private javax.swing.JLabel LNick;
    private javax.swing.JLabel LNickC;
    private javax.swing.JLabel LNome;
    private javax.swing.JLabel LSenha;
    private javax.swing.JLabel LSenhaC;
    private javax.swing.JLabel LSenhaCC;
    private javax.swing.JLabel LSexo;
    private javax.swing.JLabel LTermos;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel PCadastro;
    private javax.swing.JPanel PDirecionamento;
    private javax.swing.JPanel PGenero;
    private javax.swing.JPanel PLogin;
    private javax.swing.JPanel PMp3;
    private javax.swing.JPasswordField PSenha;
    private javax.swing.JPasswordField PSenhaC;
    private javax.swing.JPasswordField PSenhaCC;
    private javax.swing.JRadioButton RFem;
    private javax.swing.JRadioButton RMasc;
    private javax.swing.JRadioButton RTermos;
    private javax.swing.JTextField TEmail;
    private javax.swing.JTextField TIdade;
    private javax.swing.JTextField TNickC;
    private javax.swing.JTextField TNome;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JTextField login_nick;
    // End of variables declaration//GEN-END:variables

    
    class Musica extends Thread {
        
        public void run() {
            try {
  
            InputStream input = this.getClass().getResourceAsStream("/Musicas/"+musicas[cont]+".mp3");
            
            ply = new Player(input);    
            ply.play();
            
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
    }
    
}
